spring:
  redis:
    host: 172.16.18.240
    port: 6379
    database: 1
  datasource:
    url: jdbc:postgresql://172.16.18.240:5432/zhangdi_test
    driver-class-name: org.postgresql.Driver
    username: dizhang

mybatis:
  configuration:
    # 开启驼峰命名法，否则属性dId与数据库中的d_id无法匹配
    map-underscore-to-camel-case: true

logging:
  level:
    com.zhangblue.redis.cache.mapper: debug
debug: true


